#If you touch this your config might light on fire
version: 0.1

#Do you want to enable the plugin itself?
#How long do you want players to be in combat for?
#Do you want to disable the plugins for specific worlds?
combatlog:
  enabled: true
  time: 20
  disabledworlds: []

#Do you want to disallow teleporting?
#Do you want to disallow certain commands?
disallow:
  teleporting: true
  commands: []

#Do you want to kill the player when they combat log?
#Do you want to broadcast a message to the server when they combat log?
punishment:
  kill: true
  broadcast: true